// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dbLabb.Data;

#nullable disable

namespace dbLabb.Migrations
{
    [DbContext(typeof(InterestingDbContext))]
    partial class InterestingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("dbLabb.Models.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Photography",
                            PersonId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hiking",
                            PersonId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cooking",
                            PersonId = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Reading",
                            PersonId = 3
                        },
                        new
                        {
                            Id = 5,
                            Name = "Traveling",
                            PersonId = 4
                        },
                        new
                        {
                            Id = 6,
                            Name = "Gaming",
                            PersonId = 5
                        },
                        new
                        {
                            Id = 7,
                            Name = "Gardening",
                            PersonId = 6
                        },
                        new
                        {
                            Id = 8,
                            Name = "Cycling",
                            PersonId = 2
                        },
                        new
                        {
                            Id = 9,
                            Name = "Music",
                            PersonId = 3
                        },
                        new
                        {
                            Id = 10,
                            Name = "Yoga",
                            PersonId = 4
                        });
                });

            modelBuilder.Entity("dbLabb.Models.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IntrestId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("IntrestId");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IntrestId = 1,
                            Url = "https://www.photography.com"
                        },
                        new
                        {
                            Id = 2,
                            IntrestId = 2,
                            Url = "https://www.hikingadventures.com"
                        },
                        new
                        {
                            Id = 3,
                            IntrestId = 3,
                            Url = "https://www.cookingrecipes.com"
                        },
                        new
                        {
                            Id = 4,
                            IntrestId = 4,
                            Url = "https://www.bookclub.com"
                        },
                        new
                        {
                            Id = 5,
                            IntrestId = 5,
                            Url = "https://www.travelblog.com"
                        },
                        new
                        {
                            Id = 6,
                            IntrestId = 6,
                            Url = "https://www.gamingworld.com"
                        },
                        new
                        {
                            Id = 7,
                            IntrestId = 7,
                            Url = "https://www.gardeningtips.com"
                        },
                        new
                        {
                            Id = 8,
                            IntrestId = 8,
                            Url = "https://www.cyclingroutes.com"
                        },
                        new
                        {
                            Id = 9,
                            IntrestId = 9,
                            Url = "https://www.musiclovers.com"
                        },
                        new
                        {
                            Id = 10,
                            IntrestId = 10,
                            Url = "https://www.yogapractice.com"
                        });
                });

            modelBuilder.Entity("dbLabb.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastName = "Doe",
                            Name = "John",
                            PhoneNumber = "+46704523256"
                        },
                        new
                        {
                            Id = 2,
                            LastName = "Smith",
                            Name = "Jane",
                            PhoneNumber = "+46736259883"
                        },
                        new
                        {
                            Id = 3,
                            LastName = "Johnson",
                            Name = "Alice",
                            PhoneNumber = "+46789012345"
                        },
                        new
                        {
                            Id = 4,
                            LastName = "Brown",
                            Name = "Bob",
                            PhoneNumber = "+46712345678"
                        },
                        new
                        {
                            Id = 5,
                            LastName = "Davis",
                            Name = "Eve",
                            PhoneNumber = "+46798765432"
                        },
                        new
                        {
                            Id = 6,
                            LastName = "Wilson",
                            Name = "Charlie",
                            PhoneNumber = "+46756473829"
                        });
                });

            modelBuilder.Entity("dbLabb.Models.Interest", b =>
                {
                    b.HasOne("dbLabb.Models.Person", "person")
                        .WithMany("Interests")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("person");
                });

            modelBuilder.Entity("dbLabb.Models.Link", b =>
                {
                    b.HasOne("dbLabb.Models.Interest", "Interest")
                        .WithMany("Links")
                        .HasForeignKey("IntrestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");
                });

            modelBuilder.Entity("dbLabb.Models.Interest", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("dbLabb.Models.Person", b =>
                {
                    b.Navigation("Interests");
                });
#pragma warning restore 612, 618
        }
    }
}
